export const AUTHENTICATED = "AUTHENTICATED";
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_USER = 'SET_USER';
export const SET_MODEL_TYPE = 'SET_MODEL_TYPE';
export const SAVE_MEMBERS = 'SAVE_MEMBERS';
export const CHANGE_APPROVAL = 'CHANGE_APPROVAL';